
trigger:
- main

stages:
- stage:
  jobs:
  - job:

    pool:
      vmImage: 'windows-latest'

    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
    
    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

- stage:
  jobs:
  - deployment: 
    environment: sqltest.prod
    strategy:
      runOnce:
        deploy:   
          steps:    
          - task: GitHubRelease@1
            inputs:
              gitHubConnection: 'GitHub connection 1'
              repositoryName: '$(Build.Repository.Name)'
              action: 'edit'
              target: '$(Build.SourceVersion)'
              tag: '0.0.1-beta'
              title: 'Beta'
              assets: '$(Build.ArtifactStagingDirectory)/*.zip'
              assetUploadMode: 'replace'
              isPreRelease: true
              addChangeLog: false
