
trigger:
- master

variables:
- template: azure-pipelines.variables.yml
  parameters:
    publish: true

stages:
- stage: build
  jobs:
  - template: azure-pipelines.build.yml
    parameters:
      publish: true

- stage: PublishToGitHub
  dependsOn: build
  condition:  and(succeeded(),eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs: 
  - deployment: PublishGitHubReleaseJob
    environment: sqltest_prod
    strategy:
      runOnce:
        deploy:   
          steps:    
          - download: none
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              targetPath: '$(Build.ArtifactStagingDirectory)'

          - task: GitHubRelease@1
            inputs:
              gitHubConnection: 'GitHub.com'
              repositoryName: '$(Build.Repository.Name)'
              action: 'edit'
              target: '$(Build.SourceVersion)'
              tag: '$(Version)'
              title: 'Beta'
              assets: '$(Build.ArtifactStagingDirectory)/**/*'
              assetUploadMode: 'replace'
              isPreRelease: true
              addChangeLog: true


- stage: PublishToNuget
  condition:  and(succeeded(),eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  dependsOn: build
  jobs: 
  - deployment: PublishToNugetJob
    environment: sqltest-nuget
    strategy:
      runOnce:
        deploy:   
          steps:    
          - download: none
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              targetPath: '$(Build.ArtifactStagingDirectory)'

          - task: PowerShell@2
            displayName: Package Nuget Packages
            inputs:
              filePath: '$(Build.ArtifactStagingDirectory)\.build\pipeline.ps1'
              arguments: '-publish -apikey $(apikey)'
