
trigger:
- master
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: build
  pool:
    vmImage: 'windows-latest'

  jobs:
  - job:  
    steps:
    - task: NuGetToolInstaller@1

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

        
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '**/XEvent.App.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: false
        modifyOutputPath: false

   

- stage:
  displayName: Publish Github Release
  pool:
    vmImage: 'windows-latest'

  jobs:
  - deployment: 
    environment: sqltest_prod
    strategy:
      runOnce:
        deploy:   
          steps:    
          - task: GitHubRelease@1
            inputs:
              gitHubConnection: 'GitHub.com'
              repositoryName: '$(Build.Repository.Name)'
              action: 'edit'
              target: '$(Build.SourceVersion)'
              tag: '0.0.1-beta'
              title: 'Beta'
              assets: '$(Build.ArtifactStagingDirectory)/*.zip'
              assetUploadMode: 'replace'
              isPreRelease: true
              addChangeLog: false
